from HTTPRequest import HTTPRequest
from Connection import Connection
from Macro import *
 
#req=HTTPRequest("testReqPost1",isTLS=True,proxies = { 'http': 'http://127.0.0.1:8080','https': 'http://127.0.0.1:8080',},verify=False)
#req=HTTPRequest("testReqPost1",isTLS=True,verify=False)
#req=HTTPRequest("testReqPost1",connection={"verify" : False, "isTLS": True,"proxies":{ 'http': 'http://127.0.0.1:8080','https': 'http://127.0.0.1:8080',} })
con=Connection(isTLS=True,verify=False,proxies={ 'http': 'http://127.0.0.1:8080','https': 'http://127.0.0.1:8080',})
#req=HTTPRequest("testReqPost1",connection=con)
#req.printFields()
#macro=Macro(con,"testReq1","testReqPost1")
#var1=MacroVariable(0,True,"Version\":\"","\",\"build")
#var2=MacroVariable(1,False,"username=","&password")
#rule1=MacroRule(var1,var2)
#macro.addRule(rule1)
#macro.run()
#req.send()
req=HTTPRequest("reqPost2",isTLS=True,proxies = { 'http': 'http://127.0.0.1:8080','https': 'http://127.0.0.1:8080',},verify=False)
#req.printFields()
req.send()
print("time",req.elapsed)
#req.replaceString("antoine","yoo")
#req.send()
#req.printFields()
#req=HTTPRequest("testReqPost1",isTLS=True,verify=False)
#req.replaceString("en-US","yo")

#req1=HTTPRequest("reqLoginBLNET1",connection=con)
#req2=HTTPRequest("reqLoginBLNET2",connection=con)
#macro=Macro(con, "reqLoginBLNET1", "reqLoginBLNET2")
#var1=MacroVariable(0,True,"h=","\", \"")
#var2=MacroVariable(1,False,"h=", " HTTP")
#rule1=MacroRule(var1,var2)
#macro.addRule(rule1)
#macro.run()
#req=HTTPRequest("reqLoginBLNET")
#req1.send()
print(req1.response.headers)